# Python Official Image (Alpine-based: lightweight & multi-arch compatible)
FROM python:3.12.11-alpine3.22 AS base

# Set Python environment flags (No .pyc + unbuffered logs)
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    LANG=C.UTF-8 \
    PATH="/usr/local/bin:$PATH"

# Install essential system packages (Essential Alpine packages)
RUN set -eux; \
    apk update && \
    apk add --no-cache \
        ffmpeg      # Required for media processing via ffmpeg-python, yt-dlp etc. \                
        gcc         # For compiling some Python wheels pandas, pydantic (via Cython), etc. \
        musl-dev    # Libc implementation for Alpine, needed by most Python C extensions \
        libffi-dev  # Required for PyJWT, cryptographic dependencies etc. \
        zlib-dev    # Used by many core packages like needed by pandas, XlsxWriter etc.

# Install yt-dlp via pip (not available via apk reliably)
RUN pip install --no-cache-dir yt-dlp   # For YouTube video/audio download support

# Set work directory
WORKDIR /app

# Create necessary folders
RUN mkdir -p /app/media

# Copy requirements
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
