-- [ALTER TABLE]: auth_user
-- Drop columns
ALTER TABLE 
    auth_user 
DROP COLUMN username,
DROP COLUMN email,
DROP COLUMN password,
DROP COLUMN first_name,
DROP COLUMN last_name,
DROP COLUMN last_login,
DROP COLUMN is_superuser,
DROP COLUMN is_staff,
DROP COLUMN is_active,
DROP COLUMN date_joined;
-- Add columns
ALTER TABLE 
    auth_user 
ADD COLUMN first_name VARCHAR(128) NOT NULL,
ADD COLUMN last_name VARCHAR(128) NOT NULL,
ADD COLUMN email VARCHAR(256) NOT NULL,
ADD COLUMN username VARCHAR(256) NOT NULL,
ADD COLUMN password VARCHAR(128) NOT NULL,
ADD COLUMN date_joined TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN created_by INTEGER NOT NULL,
ADD COLUMN updated_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN updated_by INTEGER,
ADD COLUMN is_superuser BOOLEAN DEFAULT FALSE,
ADD COLUMN is_staff BOOLEAN DEFAULT TRUE,
ADD COLUMN is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN last_login TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
